from __future__ import annotations

from pathlib import Path
from typing import Annotated

import typer

from transfection.app import app
from transfection.services.plot_auc import format_written_auc_plot_message, run_plot_auc

NAME = "plot-auc"
HELP = "Plot AUC summaries as one box plot per slide channel."


@app.command(NAME, help=HELP)
def plot_auc(
    auc_csv: Annotated[
        Path,
        typer.Argument(
            exists=True,
            dir_okay=False,
            metavar="AUC_CSV",
            help="AUC summary CSV generated by transfection auc.",
        ),
    ],
    output: Annotated[
        Path | None,
        typer.Option(
            "--output",
            "-o",
            help="Output PNG path. Default: auc.png in the same directory as the AUC CSV.",
        ),
    ] = None,
) -> None:
    resolved_output_plot = run_plot_auc(auc_csv=auc_csv, output=output)
    typer.echo(format_written_auc_plot_message(resolved_output_plot))
